package ie.setu.domain.repository

import ie.setu.domain.Activity
import ie.setu.domain.db.Activities
import ie.setu.utils.mapToActivity
import io.github.oshai.kotlinlogging.KotlinLogging
import org.jetbrains.exposed.sql.*
import org.jetbrains.exposed.sql.SqlExpressionBuilder.eq
import org.jetbrains.exposed.sql.transactions.transaction

/**
 * Data-access object for [ie.setu.domain.Activity] records.
 *
 * Provides CRUD operations over the `activities` table and helper
 * queries for common lookups.
 */
class ActivityDAO {

    private fun normalizeDescription(description: String): String {
        return if (description.length <= Activities.DESCRIPTION_MAX_LENGTH) {
            description
        } else {
            description.take(Activities.DESCRIPTION_MAX_LENGTH)
        }
    }

    /** Returns all activities regardless of user id. */
    fun getAll(): ArrayList<Activity> {
        val activitiesList: ArrayList<Activity> = arrayListOf()
        transaction {
            Activities.selectAll().map {
                activitiesList.add(mapToActivity(it)) }
        }
        return activitiesList
    }

    /** Finds a single activity by its id, or null if missing. */
    fun findByActivityId(id: Int): Activity?{
        return transaction {
            Activities
                .selectAll().where { Activities.id eq id}
                .map{mapToActivity(it)}
                .firstOrNull()
        }
    }

    /** Returns all activities belonging to a specific [userId]. */
    fun findByUserId(userId: Int): List<Activity>{
        return transaction {
            Activities
                .selectAll().where {Activities.userId eq userId}
                .map {mapToActivity(it)}
        }
    }

    /** Returns the total distance (km) logged by a user. */
    fun totalDistanceKmByUserId(userId: Int): Double {
        return transaction {
            Activities
                .selectAll()
                .where { Activities.userId eq userId }
                .fold(0.0) { acc, row -> acc + row[Activities.distanceKm] }
        }
    }

    /** Persists a new [activity] and returns its generated id. */
    fun save(activity: Activity): Int {
        return transaction {
            val normalizedDescription = normalizeDescription(activity.description)
            if (normalizedDescription != activity.description) {
                activity.description = normalizedDescription
            }
            val activityId = Activities.insert {
                it[description] = normalizedDescription
                it[duration] = activity.duration
                it[calories] = activity.calories
                it[steps] = activity.steps
                it[distanceKm] = activity.distanceKm
                it[started] = activity.started
                it[userId] = activity.userId
            } get Activities.id
            //returns the activity id as generated by the table
            activityId
        }
    }

    /** Updates an existing activity identified by [activityId]. */
    fun updateByActivityId(activityId: Int, activityToUpdate: Activity) : Int{
        return transaction {
            val normalizedDescription = normalizeDescription(activityToUpdate.description)
            if (normalizedDescription != activityToUpdate.description) {
                activityToUpdate.description = normalizedDescription
            }
            Activities.update ({
                Activities.id eq activityId}) {
                it[description] = normalizedDescription
                it[duration] = activityToUpdate.duration
                it[calories] = activityToUpdate.calories
                it[steps] = activityToUpdate.steps
                it[distanceKm] = activityToUpdate.distanceKm
                it[started] = activityToUpdate.started
                it[userId] = activityToUpdate.userId
            }
        }
    }

    /** Deletes a single activity and returns the number of rows affected. */
    fun deleteByActivityId (activityId: Int): Int{
        return transaction{
            Activities.deleteWhere { Activities.id eq activityId }
        }
    }

    /** Deletes all activities for a user and returns how many rows were removed. */
    fun deleteByUserId (userId: Int): Int{
        return transaction{
            Activities.deleteWhere { Activities.userId eq userId }
        }
    }

}
