package ie.setu.domain.repository

import ie.setu.domain.Activity
import ie.setu.domain.db.Activities
import ie.setu.utils.mapToActivity
import io.github.oshai.kotlinlogging.KotlinLogging
import org.jetbrains.exposed.sql.*
import org.jetbrains.exposed.sql.SqlExpressionBuilder.eq
import org.jetbrains.exposed.sql.transactions.transaction

/**
 * Data-access object for [ie.setu.domain.Activity] records.
 *
 * Provides CRUD operations over the `activities` table and helper
 * queries for common lookups.
 */
class ActivityDAO {

    /** Returns all activities regardless of user id. */
    fun getAll(): ArrayList<Activity> {
        val activitiesList: ArrayList<Activity> = arrayListOf()
        transaction {
            Activities.selectAll().map {
                activitiesList.add(mapToActivity(it)) }
        }
        return activitiesList
    }

    /** Finds a single activity by its id, or null if missing. */
    fun findByActivityId(id: Int): Activity?{
        return transaction {
            Activities
                .selectAll().where { Activities.id eq id}
                .map{mapToActivity(it)}
                .firstOrNull()
        }
    }

    /** Returns all activities belonging to a specific [userId]. */
    fun findByUserId(userId: Int): List<Activity>{
        return transaction {
            Activities
                .selectAll().where {Activities.userId eq userId}
                .map {mapToActivity(it)}
        }
    }

    /** Persists a new [activity] and returns its generated id. */
    fun save(activity: Activity): Int {
        return transaction {
            val activityId = Activities.insert {
                it[description] = activity.description
                it[duration] = activity.duration
                it[calories] = activity.calories
                it[steps] = activity.steps
                it[started] = activity.started
                it[userId] = activity.userId
            } get Activities.id
            //returns the activity id as generated by the table
            activityId
        }
    }

    /** Updates an existing activity identified by [activityId]. */
    fun updateByActivityId(activityId: Int, activityToUpdate: Activity) : Int{
        return transaction {
            Activities.update ({
                Activities.id eq activityId}) {
                it[description] = activityToUpdate.description
                it[duration] = activityToUpdate.duration
                it[calories] = activityToUpdate.calories
                it[steps] = activityToUpdate.steps
                it[started] = activityToUpdate.started
                it[userId] = activityToUpdate.userId
            }
        }
    }

    /** Deletes a single activity and returns the number of rows affected. */
    fun deleteByActivityId (activityId: Int): Int{
        return transaction{
            Activities.deleteWhere { Activities.id eq activityId }
        }
    }

    /** Deletes all activities for a user and returns how many rows were removed. */
    fun deleteByUserId (userId: Int): Int{
        return transaction{
            Activities.deleteWhere { Activities.userId eq userId }
        }
    }

}
